---
# Ubuntu equivalent of: https://github.com/trimstray/the-practical-linux-hardening-guide/wiki/PAM-Module
# Covers: Password hashing, Failed attempts (faillock), Password reuse, Password quality

- name: PAM Module (Ubuntu Hardening)
  hosts: all
  become: yes
  vars:
    pam_faillock_deny: 5
    pam_faillock_unlock_time: 900
    pam_faillock_fail_interval: 900
    pam_remember: 5
    pam_pwquality_minlen: 14
    pam_pwquality_retry: 3
    login_defs_umask: '027'
    login_defs_passmaxdays: '60'
    login_defs_passmindays: '7'
    login_defs_passwarnage: '7'

  tasks:
    - name: Install PAM hardening packages
      apt:
        name: libpam-pwquality
        state: present

    - name: Set SHA-512 password hashing in login.defs
      lineinfile:
        path: /etc/login.defs
        regexp: '^#?ENCRYPT_METHOD'
        line: 'ENCRYPT_METHOD SHA512'

    - name: Configure login.defs (DevSec os-05)
      lineinfile:
        path: /etc/login.defs
        regexp: '^\s*#?\s*{{ item.key }}\s+'
        line: "{{ item.key }} {{ item.value }}"
      loop:
        - { key: 'UMASK', value: "{{ login_defs_umask }}" }
        - { key: 'PASS_MAX_DAYS', value: "{{ login_defs_passmaxdays }}" }
        - { key: 'PASS_MIN_DAYS', value: "{{ login_defs_passmindays }}" }
        - { key: 'PASS_WARN_AGE', value: "{{ login_defs_passwarnage }}" }
        - { key: 'LOGIN_RETRIES', value: '5' }
        - { key: 'LOGIN_TIMEOUT', value: '60' }
        - { key: 'UID_MIN', value: '1000' }
        - { key: 'GID_MIN', value: '1000' }
        - { key: 'ENV_SUPATH', value: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' }
        - { key: 'ENV_PATH', value: '/usr/local/bin:/usr/bin:/bin' }
      loop_control:
        label: "{{ item.key }}"

    - name: Configure faillock
      lineinfile:
        path: /etc/security/faillock.conf
        regexp: '^\s*#?\s*{{ item.key }}\s*='
        line: "{{ item.key }} = {{ item.value }}"
      loop:
        - { key: 'deny', value: "{{ pam_faillock_deny }}" }
        - { key: 'fail_interval', value: "{{ pam_faillock_fail_interval }}" }
        - { key: 'unlock_time', value: "{{ pam_faillock_unlock_time }}" }
        - { key: 'audit', value: 'true' }
        - { key: 'silent', value: 'true' }
      loop_control:
        label: "{{ item.key }}"

    - name: Add pam_faillock preauth to common-auth
      lineinfile:
        path: /etc/pam.d/common-auth
        regexp: 'auth\s+required\s+pam_faillock\.so preauth'
        line: 'auth    required    pam_faillock.so preauth'
        insertbefore: 'auth\s+\[success=1 default=ignore\].*pam_unix'
        state: present

    - name: Add pam_faillock authfail to common-auth
      lineinfile:
        path: /etc/pam.d/common-auth
        regexp: 'auth\s+\[default=die\].*pam_faillock\.so authfail'
        line: 'auth    [default=die]    pam_faillock.so authfail'
        insertafter: 'auth\s+\[success=1 default=ignore\].*pam_unix'
        state: present

    - name: Add pam_faillock to common-account
      lineinfile:
        path: /etc/pam.d/common-account
        regexp: 'account\s+required\s+pam_faillock\.so'
        line: 'account    required    pam_faillock.so'
        insertbefore: 'account\s+\[success=1 new_authtok_reqd=ignore default=ignore\].*pam_unix'
        state: present

    - name: Remove existing remember from pam_unix line
      replace:
        path: /etc/pam.d/common-password
        regexp: '\s+remember=\d+'
        replace: ''

    - name: Add remember to pam_unix in common-password
      replace:
        path: /etc/pam.d/common-password
        regexp: '(password\s+.*pam_unix\.so\s+)(.*?)(\s*)$'
        replace: '\1\2 remember={{ pam_remember }}\3'

    - name: Add or update pam_pwquality in common-password
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+requisite\s+.*pam_pwquality'
        line: 'password        requisite                       pam_pwquality.so retry={{ pam_pwquality_retry }} try_first_pass local_users_only'
        insertbefore: '^password\s+.*pam_unix'
        state: present

    - name: Configure pwquality.conf
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^\s*#?\s*{{ item.key }}\s*='
        line: "{{ item.key }} = {{ item.value }}"
      loop:
        - { key: 'minlen', value: "{{ pam_pwquality_minlen }}" }
        - { key: 'dcredit', value: '-1' }
        - { key: 'ucredit', value: '-1' }
        - { key: 'lcredit', value: '-1' }
        - { key: 'ocredit', value: '-1' }
        - { key: 'difok', value: '4' }
        - { key: 'maxrepeat', value: '3' }
      loop_control:
        label: "{{ item.key }}"
