name: Ansible Playbooks

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Playbook to run'
        required: true
        default: 'hardening.yml'
        type: choice
        options:
          - hardening.yml
          - k8s.yml

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: pip install ansible

      - name: Create SSH directory
        run: mkdir -p ~/.ssh && chmod 700 ~/.ssh

      - name: Install SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ansible_bot
          chmod 600 ~/.ssh/ansible_bot

      - name: Install SSH public keys for users playbook
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY_ANSIBLE_BOT }}" > ~/.ssh/ansible_bot.pub
          echo "${{ secrets.SSH_PUBLIC_KEY_BENTO }}" > ~/.ssh/id_ed25519.pub
          chmod 644 ~/.ssh/ansible_bot.pub ~/.ssh/id_ed25519.pub

      - name: Run Ansible playbook
        run: ansible-playbook ${{ github.event.inputs.playbook }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
